using System;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using BullyingGame.Core;
using BullyingGame.Quest;
using BullyingGame.Dialogue;
using BullyingGame.Events;
using BullyingGame.NPC;
using BullyingGame.QTE;
using BullyingGame.UI;
using BullyingGame.Cinematics;
using TMPro;
using UnityEngine.UI;

public static class Chapter12Authoring
{
    const string Data="Assets/_Game/Data/StoryPrototype/";
    const string Art="Assets/_Game/Art/Prototype/";
    static T Load<T>(string name) where T:UnityEngine.Object => AssetDatabase.LoadAssetAtPath<T>(Data+name+".asset");
    static T Asset<T>(string name) where T:ScriptableObject { var a=Load<T>(name);if(a==null){a=ScriptableObject.CreateInstance<T>();AssetDatabase.CreateAsset(a,Data+name+".asset");}return a; }
    static QuestData Q(string id) => id=="book" ? AssetDatabase.LoadAssetAtPath<QuestData>("Assets/_Game/Data/Quests/Quest_Level01_LostNotebook.asset") : Load<QuestData>("Quest_"+id);
    static void Edit(UnityEngine.Object o,Action<SerializedObject> change) { var s=new SerializedObject(o);change(s);s.ApplyModifiedPropertiesWithoutUndo();EditorUtility.SetDirty(o); }
    static void Ref(UnityEngine.Object o,string f,UnityEngine.Object v) => Edit(o,s=>s.FindProperty(f).objectReferenceValue=v);
    static void Refs(UnityEngine.Object o,string f,UnityEngine.Object[] values) => Edit(o,s=>{var p=s.FindProperty(f);p.arraySize=values.Length;for(int i=0;i<values.Length;i++)p.GetArrayElementAtIndex(i).objectReferenceValue=values[i];});
    static DialogueLine[] Lines(params string[] words) => words.Select(w=>new DialogueLine{speakerName=w.Substring(0,w.IndexOf('|')),text=w.Substring(w.IndexOf('|')+1)}).ToArray();
    static DialogueData D(string name,params string[] words) { var d=Asset<DialogueData>(name);d.lines=Lines(words);EditorUtility.SetDirty(d);return d; }
    static void Response(SerializedProperty p,string label,params string[] words)
    {p.FindPropertyRelative("label").stringValue=label;var lines=p.FindPropertyRelative("lines");lines.arraySize=words.Length;for(int i=0;i<words.Length;i++){var f=words[i].Split('|');var l=lines.GetArrayElementAtIndex(i);l.FindPropertyRelative("speakerName").stringValue=f[0];l.FindPropertyRelative("text").stringValue=f[1];l.FindPropertyRelative("voiceClip").objectReferenceValue=null;}}
    static QuestData Quest(string asset,string id,string title,QuestData previous,params string[] objectives)
    {var q=asset=="book"?Q("book"):Asset<QuestData>("Quest_"+asset);q.questId=id;q.questTitle=title;q.questDescription=title;q.prerequisites=previous==null?new QuestData[0]:new[]{previous};q.objectives=objectives.Select(w=>{var p=w.Split('|');return new QuestObjective{objectiveId=p[0],description=p[1],requiredAmount=1};}).ToArray();Edit(q,s=>{s.FindProperty("completionMessage").stringValue="Langkah ini selesai. Ikuti tujuan berikutnya.";s.FindProperty("routeChoiceId").stringValue="";});return q;}
    static void Quiz(NarrativeChapterData c,string[] questions)
    {Edit(c,s=>{var arr=s.FindProperty("reflections");arr.arraySize=questions.Length;for(int i=0;i<questions.Length;i++){var f=questions[i].Split('|');var p=arr.GetArrayElementAtIndex(i);p.FindPropertyRelative("questionText").stringValue=f[0];var opts=p.FindPropertyRelative("options");opts.arraySize=3;for(int j=0;j<3;j++)opts.GetArrayElementAtIndex(j).stringValue=f[j+1];p.FindPropertyRelative("correctOptionIndex").intValue=int.Parse(f[4]);p.FindPropertyRelative("educationalExplanation").stringValue=f[5];}});}
    public static string DataPass()
    {
        if(Application.isPlaying)throw new Exception("Edit Mode required");
        string backup="Logs/BeforeChapter12_"+DateTime.Now.ToString("yyyyMMdd_HHmmss");Directory.CreateDirectory(backup);
        File.Copy("Assets/_Game/Scenes/Levels/Level_01/Level01.unity",backup+"/Level01.unity");
        foreach(var path in AssetDatabase.FindAssets("t:DialogueData",new[]{"Assets/_Game/Data"}).Select(AssetDatabase.GUIDToAssetPath))
        {var d=AssetDatabase.LoadAssetAtPath<DialogueData>(path);if(d.lines==null)continue;foreach(var line in d.lines){line.speakerName=Rename(line.speakerName);line.text=Rename(line.text);}EditorUtility.SetDirty(d);}
        foreach(var path in AssetDatabase.FindAssets("t:QuestData",new[]{"Assets/_Game/Data"}).Select(AssetDatabase.GUIDToAssetPath))
        {var q=AssetDatabase.LoadAssetAtPath<QuestData>(path);q.questTitle=Rename(q.questTitle);q.questDescription=Rename(q.questDescription);foreach(var o in q.objectives)o.description=Rename(o.description);EditorUtility.SetDirty(q);}
        foreach(var path in AssetDatabase.FindAssets("t:NPCData",new[]{"Assets/_Game/Data"}).Select(AssetDatabase.GUIDToAssetPath)){var n=AssetDatabase.LoadAssetAtPath<NPCData>(path);n.npcName=Rename(n.npcName);n.description=Rename(n.description);EditorUtility.SetDirty(n);}
        for(int i=1;i<=5;i++)Edit(Load<NarrativeChapterData>("Chapter0"+i),s=>{s.FindProperty("playerName").stringValue=Rename(s.FindProperty("playerName").stringValue);s.FindProperty("closingMessage").stringValue=Rename(s.FindProperty("closingMessage").stringValue);s.FindProperty("allowsDialogueChoices").boolValue=i==1;});
        D("Opening_Victim","Narasi|Pagi di sekolah. Aji baru mengenal Denis, Ari, dan kelompok Billy. Hari ini ia melihat bagaimana satu kejadian bisa terasa berbeda bagi setiap orang.","Billy|Denis, jangan lewat sini kalau tidak membawa uang jajan.","Denis|Aku hanya mau masuk sekolah. Tolong beri jalan.","Bima|Billy, bel sudah mau bunyi. Sudahlah.","Billy|Diam. Aku cuma bercanda, kan?","Ari|Aku melihat Denis mundur. Aku takut kalau maju, mereka akan menjadikanku sasaran berikutnya.","Aji|Denis terlihat tidak nyaman. Aku belum tahu ceritanya; aku harus mendengarkan dulu.","Narasi|Aji menjadi jembatan untuk mengenal mereka. Mendengar kebutuhan seseorang lebih dahulu membuka kemungkinan membantu dengan aman.","Aji|Aku akan menemui Denis di halaman.");
        var meet=D("Dimas_Listen","Aji|Denis, tadi aku melihat Billy menghalangi jalanmu. Kamu mau ditemani?","Denis|Jangan keras-keras. Mereka sering menungguku, dan aku tidak ingin ini jadi tontonan.","Aji|Aku belum tahu semuanya. Aku ingin memahami apa yang kamu butuhkan.","Denis|Buku tugasku juga hilang sejak mereka mendatangi mejaku. Besok harus dikumpulkan. Aku sudah sulit fokus akhir-akhir ini.");
        Edit(meet,s=>{s.FindProperty("choiceId").stringValue="aji_first_response";var p=s.FindProperty("responses");p.arraySize=3;
            Response(p.GetArrayElementAtIndex(0),"Aku dengarkan. Kalau kamu setuju, kita cari bukumu bersama.","Aji|Aku tidak akan menyebarkan ceritamu. Apa yang paling ingin kamu bantu sekarang?","Denis|Terima kasih. Aku ingin bukuku kembali, tanpa membuat mereka makin marah.");
            Response(p.GetArrayElementAtIndex(1),"Kita bikin Billy malu di depan semua orang!","Aji|Kalau semua orang tahu, Billy pasti malu!","Denis|Tolong jangan. Kalau kamu memanas-manasi mereka, aku yang mereka tunggu sepulang sekolah.","Narasi|Aji perlu menghadapi respons Billy, lalu memperbaiki cara membantu agar Denis tidak semakin terpapar.");
            Response(p.GetArrayElementAtIndex(2),"Aku tidak mau ikut urusan ini. Selesaikan sendiri saja.","Aji|Aku takut ikut terseret. Aku pergi dulu.","Denis|Aku mengerti kamu takut. Tapi aku jadi merasa benar-benar sendirian.","Narasi|Ari melihat percakapan itu. Aji masih memiliki kesempatan untuk memahami dampak sikapnya.");});
        D("Aji_Route_Support","Aji|Aku datang untuk mendengar, bukan menentukan keputusanmu.","Denis|Buku bersampul biru itu terakhir kulihat dekat bangku. Ada namaku di halaman pertama.","Aji|Aku akan mencarinya. Kalau ada ancaman, kita menjauh dan mencari pendamping.");
        D("Aji_Route_Provoke","Aji|Billy, semua orang perlu tahu kamu mengambil barang Denis!","Billy|Kamu menuduhku di depan teman-temanku? Nanti Denis yang menjelaskan.","Aji|Aku membuat Denis makin terancam. Aku akan menghentikan konfrontasi ini dan menemuinya.");
        D("Aji_Route_Repair","Aji|Denis, tadi aku memanas-manasi Billy tanpa bertanya kepadamu. Aku minta maaf.","Denis|Aku ingin dibantu, tetapi jangan jadikan aku sasaran baru.","Aji|Aku akan mengikuti batasmu. Kita mulai dari buku yang kamu butuhkan.");
        D("Aji_Route_Ari","Ari|Aji, aku juga takut. Tapi menyuruh Denis menghadapi semuanya sendiri membuatnya makin terisolasi.","Aji|Aku mengira pergi berarti tidak menambah masalah.","Ari|Kamu bisa kembali dan bertanya. Menemani tidak harus berarti melawan Billy.");
        D("Aji_Route_Return","Aji|Denis, aku tadi mengabaikanmu. Kalau kamu masih berkenan, aku ingin membantu dengan cara yang kamu anggap aman.","Denis|Bantu cari bukuku, ya. Jangan menyebarkan ceritaku.","Aji|Aku akan menghormati itu.");
        D("Raka_Request","Denis|Bukuku perlu untuk tugas besok. Aku kehilangan catatan saat sedang berusaha mengejar pelajaran yang tertinggal.","Aji|Aku membantu karena kamu membutuhkannya, bukan karena perintah Billy. Aku cari di halaman dulu.","Denis|Ada namaku di dalam. Bawa kembali kepadaku kalau sudah ketemu.");
        D("Raka_Return","Aji|Ini bukumu, Denis. Namamu ada di halaman pertama.","Denis|Terima kasih. Bukunya kembali, tetapi aku masih takut bertemu mereka.","Aji|Aku paham. Mengembalikan barang belum menyelesaikan ancaman. Kita bicara tentang langkah yang aman.");
        var encounter=AssetDatabase.LoadAssetAtPath<DialogueData>("Assets/_Game/Data/Dialogues/Dialogue_Level01_Notebook_Confrontation.asset");encounter.lines=Lines("Billy|Mau membawa buku Denis? Kalian sekarang kompak, ya?","Aji|Ini buku tugasnya. Kami ingin membawanya kembali.","Fajar|Coba tahan kalau memang berani.","Narasi|Kelompok Billy menghalangi Aji. QTE berikutnya menentukan apakah buku langsung diamankan atau perlu dicari lagi.");EditorUtility.SetDirty(encounter);
        D("Dimas_Extortion","Denis|Mereka meminta uang jajanku lagi. Kalau aku menolak, mereka bilang akan menungguku setelah sekolah.","Aji|Itu ancaman, bukan kewajibanmu membayar.","Denis|Aku belum berani mengadu. Tolong jangan ceritakan ke semua orang.","Aji|Aku akan bertanya kepada Pak Bambang tentang pendampingan yang aman, dengan informasi seperlunya.");
        D("Teacher_Extortion","Aji|Pak, Denis diancam dan diminta uang. Ia takut pembalasannya. Saya ingin tahu cara mendampingi tanpa membuatnya makin terpapar.","Pak Bambang|Terima kasih menyampaikan fakta. Jangan hadapi kelompok itu sendiri. Saya akan mendekati Denis dengan hati-hati dan memeriksa keselamatannya.","Aji|Dia belum siap bercerita banyak.","Pak Bambang|Kita beri ruang. Dukungan perlu berlanjut, bukan memaksa ia langsung merasa aman.");
        D("Dimas_Escort","Aji|Mau berjalan bersama ke tempat yang lebih tenang?","Denis|Boleh. Tolong jalan dekat denganku, jangan mendahului jauh.","Aji|Kita menuju area hijau. Kita bisa berhenti kalau kamu perlu.");
        D("Dimas_Safe","Aji|Kita sudah sampai. Kamu ingin duduk atau bicara sebentar?","Denis|Aku sedikit lebih tenang. Tapi besok aku tetap harus melewati mereka.","Aji|Aku tidak akan menganggap masalah selesai hanya karena kita sudah di sini. Kita susun pendampingan untuk berikutnya.");
        D("Nara_Witness","Ari|Aku melihat Billy menghalangi Denis tadi. Aku memilih diam karena takut ikut jadi sasaran.","Aji|Kamu bisa menjelaskan fakta kepada pendamping, tanpa menjadikan Denis tontonan.","Ari|Aku mau belajar membantu. Aku akan bertanya kepada Denis sebelum menyampaikan cerita pribadinya.");
        var plan=D("Teacher_Plan","Pak Bambang|Aji, apa langkah berikutnya yang ingin kamu ajukan? Denis tetap perlu dilibatkan dalam keputusan.");
        Edit(plan,s=>{s.FindProperty("choiceId").stringValue="aji_followup";var p=s.FindProperty("responses");p.arraySize=3;
            Response(p.GetArrayElementAtIndex(0),"Susun pendampingan bersama Denis dan Ari, dengan menjaga privasinya.","Aji|Kita tanyakan batas Denis dan siapa yang boleh mendampingi.","Pak Bambang|Baik. Kita periksa lagi keadaannya dan awasi risiko ancaman berikutnya.");
            Response(p.GetArrayElementAtIndex(1),"Sebarkan kejadian ini supaya Billy dipermalukan.","Aji|Kalau kita sebarkan, Billy mungkin berhenti.","Pak Bambang|Cerita Denis bukan alat untuk mempermalukan. Menyebarkannya dapat meningkatkan risiko. Kita batasi informasi kepada pihak yang menangani.","Aji|Saya akan memperbaiki rencana dan meminta persetujuan Denis.");
            Response(p.GetArrayElementAtIndex(2),"Saya ajak Billy berkelahi saja supaya kapok.","Aji|Saya ingin menyelesaikannya dengan berkelahi.","Pak Bambang|Kekerasan menambah risiko bagi kalian dan Denis. Kita hentikan ancaman melalui pendampingan dan penanganan sekolah.","Aji|Saya akan menjauh dari konfrontasi dan ikut rencana yang lebih aman.");});
        var friend=Quest("ch01_friend","ch01_meet_denis","Temui Denis: dengarkan sebelum bertindak",null,"listen_friend|Temui Denis dan pilih respons Aji");
        var good=Quest("ch01_route_support","ch01_route_support","Mulai dari kebutuhan Denis",friend,"route|Dengarkan lokasi buku dan batas Denis");
        var provoke=Quest("ch01_route_provoke","ch01_route_provoke","Akibat memanas-manasi",friend,"confront|Temui Billy tanpa kekerasan","repair|Kembali ke Denis dan perbaiki cara membantu");
        var ignore=Quest("ch01_route_ignore","ch01_route_ignore","Kesempatan untuk kembali hadir",friend,"witness|Dengarkan Ari tentang dampak mengabaikan","repair|Kembali ke Denis dan tawarkan bantuan");
        var routes=new[]{good,provoke,ignore};for(int i=0;i<3;i++){int index=i;Edit(routes[i],s=>{s.FindProperty("routeChoiceId").stringValue="aji_first_response";s.FindProperty("routeChoiceIndex").intValue=index;});}
        var book=Quest("book","quest_level01_lost_notebook","Buku tugas Denis yang hilang",friend,"accept_request|Tanyakan buku tugas kepada Denis","find_notebook|Cari buku; bila direbut, cari lokasi barunya","return_notebook|Kembalikan buku kepada Denis");
        var ext=Q("ch01_extortion");ext.prerequisites=new[]{book};EditorUtility.SetDirty(ext);
        var c1=Load<NarrativeChapterData>("Chapter01");Refs(c1,"missions",new UnityEngine.Object[]{friend,good,provoke,ignore,book,ext,Q("ch01_escort"),Q("ch01_witness"),Q("ch01_reflection")});
        Edit(c1,s=>{s.FindProperty("perspective").enumValueIndex=(int)POVType.Protagonist;s.FindProperty("playerName").stringValue="Aji";s.FindProperty("chapterTitle").stringValue="Sebelum memahami • Halaman sekolah";s.FindProperty("closingMessage").stringValue="Aji mulai memahami bahwa membantu memerlukan persetujuan dan perhatian pada risiko. Buku Denis kembali, tetapi ancaman dan rasa takut belum hilang. Berikutnya kamu menjalani hari sekolah dari sudut pandang Denis.";});
        var opening=D("Opening_Denis","Narasi|Hari berikutnya. Kini kamu bermain sebagai Denis. Kejadian kemarin masih terasa, meski buku tugasmu sudah kembali.","Denis|Aku mencoba belajar semalam, tapi setiap membaca aku teringat ancaman Billy. Aku tidur sedikit sekali.","Aji|Kalau kamu membutuhkan teman, aku ada. Kamu boleh menentukan kapan ingin bercerita.","Denis|Aku ingin mengadu, tapi takut mereka menungguku. Di rumah aku juga belum tahu bagaimana menjelaskan semuanya.","Ari|Aku melihat Denis makin sering sendiri. Aku belum berani mendekat saat kelompok Billy ada.","Pak Bambang|Denis, nanti kita mencoba satu soal di papan tulis. Kamu boleh mengerjakannya pelan-pelan.","Denis|Aku biasanya bisa. Hari ini pikiranku seperti penuh suara lain.","Narasi|Tekanan dapat menyulitkan konsentrasi. Nilai pelajaran bukan ukuran apakah seseorang pantas dihormati.");
        Edit(opening,s=>{s.FindProperty("contextChoiceId").stringValue="aji_first_response";var p=s.FindProperty("contextResponses");p.arraySize=3;
            Response(p.GetArrayElementAtIndex(0),"","Denis|Kemarin Aji mendengarkan tanpa memaksaku. Aku tahu ada seseorang, walaupun rasa takutku belum hilang.");
            Response(p.GetArrayElementAtIndex(1),"","Denis|Kemarin konfrontasi Aji membuatku khawatir. Ia sudah meminta maaf, tetapi aku masih takut Billy membalas.");
            Response(p.GetArrayElementAtIndex(2),"","Denis|Kemarin Aji sempat pergi, lalu kembali. Aku ingin percaya, tetapi perlu waktu untuk merasa aman.");});
        D("Denis_Math_Intro","Pak Bambang|Denis, coba 7 × 6 + 8. Kerjakan perkalian lebih dahulu. Tidak perlu terburu-buru.","Denis|Baik, Pak. Aku mencoba fokus.","Narasi|Pilih jawaban. Tidak ada timer atau pengurangan poin; adegan berikutnya tetap berlanjut apa pun jawabanmu.");
        D("DenisPressure_MathCorrect","Denis|Tujuh kali enam empat puluh dua, ditambah delapan: lima puluh.","Pak Bambang|Benar. Langkahmu tepat.","Billy|Wah, sok pintar. Paling cuma hafal dari buku yang dicari Aji.","Denis|Bahkan saat benar, mereka tetap mengejek. Aku takut mengangkat kepala.","Pak Bambang|Billy, hentikan komentar itu. Denis berhak belajar tanpa direndahkan.","Narasi|Teguran menghentikan ejekan saat itu, tetapi Denis masih membawa ketakutannya ke waktu istirahat.");
        D("DenisPressure_MathWrong","Denis|Aku... kehilangan urutannya. Aku memilih jawaban yang keliru.","Billy|Soal begitu saja tidak bisa. Memalukan.","Denis|Semalam aku mencoba belajar. Sekarang pikiranku kosong karena takut mereka tertawa.","Pak Bambang|Hentikan ejekannya, Billy. Jawaban yang benar 50: perkalian lebih dulu, lalu tambah 8. Salah menjawab adalah bagian dari belajar.","Narasi|Kesalahan hitung tidak membenarkan hinaan. Tekanan Denis belum hilang ketika pelajaran selesai.");
        D("Denis_Lunch_Intro","Narasi|Istirahat. Denis berjalan ke kantin untuk membeli makanan dengan sisa uang jajannya.","Bu Sari|Ini rotimu, Denis. Duduklah di tempat yang teduh.","Denis|Terima kasih, Bu. Aku belum makan sejak pagi.","Billy|Denis, makananmu untuk kami. Jangan pelit.","Denis|Ini makanan yang baru kubeli. Aku membutuhkannya.","Narasi|Kelompok Billy menutup jalan. Usaha Denis tidak mengubah keputusan mereka merampas makanan. Kamu dapat mengikuti QTE atau mengaktifkan Bantuan QTE di Pengaturan.");
        D("DenisPressure_FoodEffort","Denis|Aku mencoba memegang makanan itu dan meminta mereka berhenti.","Billy|Lepaskan. Kami yang menentukan.","Narasi|Makanan tetap direbut. Usaha Denis terlihat, tetapi jumlah dan ancaman kelompok membuat pilihannya terbatas.","Denis|Aku sudah berusaha. Ini tetap bukan salahku.");
        D("DenisPressure_FoodTimeout","Denis|Tubuhku kaku. Aku tidak sempat bergerak saat mereka mendekat.","Billy|Begitu dong. Tidak usah melawan.","Narasi|Makanan tetap direbut. Membeku saat terancam bukan persetujuan dan bukan kegagalan moral Denis.","Denis|Aku butuh tempat untuk menjauh dari mereka.");
        D("DenisPressure_Threat","Billy|Uangmu juga sini. Kalau kamu mengadu ke guru atau orang tua, kamu akan menyesal. Aku tunggu setelah sekolah.","Denis|Aku takut. Uang itu untuk pulang.","Fajar|Jangan cari masalah. Diam saja.","Denis|Kalau aku cerita, bagaimana kalau ancaman itu benar-benar terjadi? Aku belum sanggup menjelaskan.","Narasi|Ancaman membatasi rasa aman Denis. Tanggung jawab pemalakan tetap berada pada pelaku; Denis tidak harus melawan sendirian.");
        D("Denis_Ari","Ari|Denis, aku melihat mereka mengambil makananmu. Maaf aku tidak maju. Aku takut juga.","Denis|Aku belum siap mengadu. Jangan kirim cerita atau foto ke grup.","Ari|Aku tidak akan menyebarkannya. Aku bisa duduk di dekatmu dan menemani ketika kamu siap mencari pendamping.","Denis|Untuk sekarang, temani aku sebentar. Besok sekolah terasa menakutkan.","Ari|Aku tinggal di sini. Kita bisa mencari jalan yang lebih aman bersama.","Narasi|Kehadiran Ari adalah awal dukungan, bukan penyelesaian instan. Keberanian saksi dan penanganan sekolah perlu berkembang pada chapter berikutnya.");
        var math=Quest("ch02_arithmetic","ch02_arithmetic","Belajar di bawah tekanan",Q("ch01_reflection"),"solve|Temui Pak Bambang di kelas dan kerjakan soal");
        var lunch=Quest("ch02_lunch","ch02_lunch","Istirahat yang tidak tenang",math,"encounter|Beli makanan di kantin dan jalani kejadian");
        var pressure=Quest("ch02_pressure","ch02_pressure","Ancaman yang membungkam",lunch,"hear_threat|Hadapi percakapan Billy di halaman");
        var witness=Quest("ch02_witness","ch02_witness","Seseorang melihat",pressure,"witness|Temui Ari di bangku taman");
        var reflection=Q("ch02_reflection");reflection.questTitle="Refleksi: memahami tekanan Denis";reflection.prerequisites=new[]{witness};EditorUtility.SetDirty(reflection);
        var c2=Load<NarrativeChapterData>("Chapter02");Refs(c2,"missions",new UnityEngine.Object[]{math,lunch,pressure,witness,reflection});Ref(c2,"openingDialogue",opening);
        Edit(c2,s=>{s.FindProperty("perspective").enumValueIndex=(int)POVType.Victim;s.FindProperty("playerName").stringValue="Denis";s.FindProperty("chapterTitle").stringValue="Hari yang terasa panjang • POV Denis";s.FindProperty("closingMessage").stringValue="Jawaban benar atau salah tidak menghentikan pilihan Billy merendahkan. Makanan dirampas dan ancaman membuat Denis takut mencari bantuan. Ari mulai hadir; dukungan dan keselamatan perlu ditindaklanjuti, bukan memaksa Denis langsung berani.";s.FindProperty("allowsDialogueChoices").boolValue=false;});
        Quiz(c2,new[]{"Denis tetap diejek ketika menjawab benar maupun salah. Ini menunjukkan…|Denis harus selalu mendapat nilai sempurna|Perundungan adalah tindakan pelaku, bukan akibat jawaban korban|Salah menjawab membolehkan ejekan|1|Benar atau salah dalam pelajaran tidak menghapus hak Denis untuk belajar dengan aman.","Denis takut mengadu karena diancam. Dukungan awal yang sesuai adalah…|Memaksa ia mengadu di depan kelompok Billy|Menyebarkan ceritanya agar ramai|Menemani, menjaga privasi, dan mencari pendampingan yang aman|2|Ancaman membuat mencari bantuan terasa berisiko. Dengarkan dan siapkan bantuan tanpa menyalahkan atau meninggalkan korban."});
        var qte=Asset<QTEData>("QTE_DenisFood");qte.qteId="denis_food_effort";qte.qteType=QTEType.RapidPress;qte.timeLimit=5;qte.requiredPressCount=6;Edit(qte,s=>{s.FindProperty("narrativeEffort").boolValue=true;s.FindProperty("narrativeInstruction").stringValue="Coba tahan [{input}] • Makanan akan tetap direbut.\nKamu tidak bersalah.";});
        var arithmetic=Asset<NarrativeActivityData>("Activity_DenisMath");Edit(arithmetic,s=>{s.FindProperty("kind").enumValueIndex=0;s.FindProperty("instruction").stringValue="Papan tulis: 7 × 6 + 8 = ?\nKerjakan perkalian dahulu. Pilih satu jawaban; tidak ada batas waktu.";var a=s.FindProperty("answers");a.arraySize=3;var answers=new[]{"50  —  42 + 8","98  —  7 × 14","48"};for(int i=0;i<3;i++)a.GetArrayElementAtIndex(i).stringValue=answers[i];s.FindProperty("correctAnswer").intValue=0;s.FindProperty("successDialogue").objectReferenceValue=Load<DialogueData>("DenisPressure_MathCorrect");s.FindProperty("failureDialogue").objectReferenceValue=Load<DialogueData>("DenisPressure_MathWrong");});
        var coercion=Asset<NarrativeActivityData>("Activity_DenisFood");Edit(coercion,s=>{s.FindProperty("kind").enumValueIndex=1;s.FindProperty("effortQTE").objectReferenceValue=qte;s.FindProperty("successDialogue").objectReferenceValue=Load<DialogueData>("DenisPressure_FoodEffort");s.FindProperty("failureDialogue").objectReferenceValue=Load<DialogueData>("DenisPressure_FoodTimeout");});
        // Keep later prototype chapters playable with the new identities. Deep writing remains focused on 1–2.
        Edit(Load<NarrativeChapterData>("Chapter04"),s=>s.FindProperty("playerName").stringValue="Denis");
        D("Opening_Boundaries","Narasi|Taman lingkungan, sepulang sekolah. Denis kembali merasakan tekanan dari ejekan berulang di grup.","Denis|Aku takut membuka pesan. Di kelas aku makin sulit fokus; aku merasa semua orang sedang membicarakanku.","Aji|Kesulitanmu bukan alasan mereka merendahkan. Aku ingin menemani dengan mengikuti batasmu.","Denis|Aku ingin menyimpan bukti, tapi jangan kirim ulang ke orang lain.","Ari|Aku dapat membantu menyimpan seperlunya. Kamu menentukan siapa boleh melihat.","Denis|Aku ingin Pak Bambang tahu, dengan seseorang di sampingku.","Aji|Kita susun langkahnya pelan-pelan. Kamu tidak harus menghadapi mereka sendiri.","Narasi|Dukungan yang berlanjut membantu Denis menetapkan batas; keselamatannya tetap menjadi tujuan.");
        D("Park_Check","Aji|Denis, bagaimana kabarmu setelah kejadian kemarin?","Denis|Aku merasa bersalah karena takut. Belajarku tertinggal.","Aji|Yang bersalah adalah tindakan yang menyakitimu. Kita bisa meminta pendampingan dan bantuan belajar.");
        D("Park_Boundary","Denis|Aku ingin mereka berhenti menghubungiku dan menyebarkan ejekan. Aku belum mau bertemu tanpa pendamping.","Aji|Aku akan menghormati batasmu dan menemani ketika kamu siap.");
        AssetDatabase.SaveAssets();return "Saved Chapter 1: 3 Aji routes / Denis notebook; Chapter 2: arithmetic, coercion, threat, Ari and reflections. Names updated without deleting historical assets.";
    }
    static string Rename(string text)
    {
        var result=(text??"").Replace("Arisi","Narasi");
        var before=new[]{"Arga","Dimas","Raka","Nara","Bu Nadia"};var after=new[]{"Aji","Denis","Billy","Ari","Pak Bambang"};
        for(int i=0;i<before.Length;i++)result=System.Text.RegularExpressions.Regex.Replace(result,"\\b"+before[i]+"\\b",after[i]);
        return result;
    }
}
