using System;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Playables;
using UnityEngine.Timeline;
using UnityEditor;
using UnityEditor.SceneManagement;
using TMPro;
using Unity.Cinemachine;
using BullyingGame.Core;
using BullyingGame.UI;
using BullyingGame.Dialogue;
using BullyingGame.Cinematics;
using BullyingGame.Quest;
using BullyingGame.Quiz;
using BullyingGame.Events;

public static class CleanChapterAuthoring
{
 const string Data="Assets/_Game/Data/StoryPrototype/";
 const string Art="Assets/_Game/Art/Prototype/";
 const string BaseScene="Assets/_Game/Scenes/Levels/Level_01/Level01.unity";
 static T Load<T>(string name) where T:UnityEngine.Object=>AssetDatabase.LoadAssetAtPath<T>(Data+name+".asset");
 static void Edit(UnityEngine.Object o, Action<SerializedObject> f){var s=new SerializedObject(o);f(s);s.ApplyModifiedPropertiesWithoutUndo();EditorUtility.SetDirty(o);}
 static T Field<T>(UnityEngine.Object o,string f) where T:UnityEngine.Object => new SerializedObject(o).FindProperty(f).objectReferenceValue as T;
 static void Ref(UnityEngine.Object o,string f,UnityEngine.Object value)=>Edit(o,s=>s.FindProperty(f).objectReferenceValue=value);
 static void Refs(UnityEngine.Object o,string f,UnityEngine.Object[] values)=>Edit(o,s=>{var p=s.FindProperty(f);p.arraySize=values.Length;for(int i=0;i<values.Length;i++)p.GetArrayElementAtIndex(i).objectReferenceValue=values[i];});
 static T C<T>(GameObject g) where T:Component{var c=g.GetComponent<T>();return c!=null?c:g.AddComponent<T>();}
 static GameObject Child(Transform p,string n,bool ui=false){var t=p.Find(n);if(t!=null)return t.gameObject;var g=ui?new GameObject(n,typeof(RectTransform)):new GameObject(n);g.transform.SetParent(p,false);return g;}
 static void Rect(GameObject g,Vector2 a,Vector2 pivot,Vector2 pos,Vector2 size){var r=g.GetComponent<RectTransform>();r.anchorMin=r.anchorMax=a;r.pivot=pivot;r.anchoredPosition=pos;r.sizeDelta=size;r.localScale=Vector3.one;r.localRotation=Quaternion.identity;}
 static TMP_Text Label(Transform p,string n,string text,Vector2 a,Vector2 pivot,Vector2 pos,Vector2 size,float font){var g=Child(p,n,true);Rect(g,a,pivot,pos,size);var t=C<TextMeshProUGUI>(g);t.font=TMP_Settings.defaultFontAsset;t.text=text;t.fontSize=font;t.enableAutoSizing=false;t.alignment=TextAlignmentOptions.TopLeft;t.textWrappingMode=TextWrappingModes.Normal;t.color=new Color(.93f,.97f,.98f);t.raycastTarget=false;return t;}
 static GameObject GO(UnityEngine.Object o)=>o is GameObject g?g:((Component)o).gameObject;
 static void Place(Transform t,Vector3 p,float yaw=180){t.SetPositionAndRotation(p,Quaternion.Euler(0,yaw,0));}
 static DialogueData D(string n,params string[] lines){var d=Load<DialogueData>(n);if(d==null){d=ScriptableObject.CreateInstance<DialogueData>();AssetDatabase.CreateAsset(d,Data+n+".asset");}d.lines=lines.Select(l=>new DialogueLine{speakerName=l.Split('|')[0],text=l.Substring(l.IndexOf('|')+1)}).ToArray();EditorUtility.SetDirty(d);return d;}
 public static string DataPass()
 {
 if(Application.isPlaying)throw new Exception("Edit Mode required");
 Directory.CreateDirectory("Logs/BeforeCleanPresentation");File.Copy(BaseScene,"Logs/BeforeCleanPresentation/Level01.unity",true);
 for(int i=1;i<=5;i++){var c=Load<NarrativeChapterData>("Chapter0"+i);Edit(c,s=>s.FindProperty("sceneName").stringValue="Level0"+i);var q=Load<QuestData>("Quest_ch0"+i+"_reflection");q.questTitle=i==1?"Memahami kejadian Denis":i==2?"Memahami tekanan Denis":"Memahami pengalaman teman";q.objectives[0].description="Jawab dua pertanyaan tentang kejadian tadi";EditorUtility.SetDirty(q);}
 Edit(Load<NarrativeChapterData>("Chapter01"),s=>{var q=s.FindProperty("reflections").GetArrayElementAtIndex(1);q.FindPropertyRelative("questionText").stringValue="Billy merebut dan menyembunyikan buku Denis. Siapa yang bertanggung jawab atas tindakan itu?";var options=q.FindPropertyRelative("options");options.GetArrayElementAtIndex(0).stringValue="Denis, karena tidak mampu mempertahankan bukunya";options.GetArrayElementAtIndex(1).stringValue="Aji, karena belum berhasil menghentikannya";options.GetArrayElementAtIndex(2).stringValue="Billy dan teman-teman yang melakukan perundungan";q.FindPropertyRelative("correctOptionIndex").intValue=2;q.FindPropertyRelative("educationalExplanation").stringValue="Tanggung jawab berada pada pelaku. Denis tetap berhak mendapat dukungan, dan Aji dapat mencari bantuan tanpa harus melawan kelompok itu sendirian.";});
 D("Opening_Victim","Narasi|Pagi di halaman sekolah. Bel belum berbunyi, tetapi Denis sudah berharap hari ini cepat selesai.","Aji|Aku Aji, baru masuk sekolah ini. Aku ingin mengenal teman-teman di sini.","Denis|Buku tugasku belum ketemu. Aku sudah mengerjakannya semalam...","Billy|Denis, jangan lewat sini kalau tidak membawa uang jajan.","Bima|Billy, bel sebentar lagi. Kita masuk saja.","Fajar|Sudah, Denis. Turuti saja Billy biar cepat selesai.","Denis|Aku hanya mau masuk sekolah. Tolong beri jalan.","Billy|Santai. Aku cuma bercanda, kan?","Ari|Aku Ari. Aku melihat Denis mundur, tapi aku takut jadi sasaran berikutnya.","Pak Bambang|Selamat pagi. Saya Pak Bambang. Kalau ada yang mengganggu kalian, saya bersedia mendengarkan.","Bu Sari|Anak-anak, jangan lupa sarapan. Kantin sudah buka.","Aji|Denis terlihat tidak nyaman. Aku akan menemuinya dan mendengar apa yang ia butuhkan.","Narasi|Hari ini Aji mulai mengenal mereka. Setiap orang membawa cerita yang belum terlihat dari luar.");
 D("Denis_Math_Intro","Pak Bambang|Denis, coba kerjakan 7 × 6 + 8 di papan tulis. Tidak perlu terburu-buru.","Denis|Baik, Pak. Aku mencoba fokus.");
 D("Denis_Lunch_Intro","Bu Sari|Ini rotimu, Denis. Duduklah di tempat yang teduh.","Denis|Terima kasih, Bu. Aku belum makan sejak pagi.");
 var confrontation=D("DenisPressure_FoodConfrontation","Billy|Denis, makananmu untuk kami. Jangan pelit.","Denis|Ini makanan yang baru kubeli. Aku belum sarapan.","Fajar|Dengar Billy. Jangan membuat masalah.","Denis|Mereka menutup jalan. Aku ingin pergi, tapi tubuhku mulai kaku.");Ref(Load<NarrativeActivityData>("Activity_DenisFood"),"confrontationDialogue",confrontation);
 var lunch=Load<QuestData>("Quest_ch02_lunch");lunch.objectives[0].description="Datangi kantin saat istirahat";EditorUtility.SetDirty(lunch);
 var vendor=Load<BullyingGame.NPC.NPCData>("NPC_BuSari");vendor.interactionPrompt="Bicara";EditorUtility.SetDirty(vendor);
 AssetDatabase.SaveAssets();return "Saved scene IDs, story-based questions and character introduction; removed technical narration from the classroom/canteen.";
 }
 static Sprite Arrow()
 {string path=Art+"QuestDirection.asset";var sprite=AssetDatabase.LoadAllAssetsAtPath(path).OfType<Sprite>().FirstOrDefault();if(sprite!=null)return sprite;var texture=new Texture2D(64,64,TextureFormat.RGBA32,false);texture.name="QuestDirection";for(int y=0;y<64;y++)for(int x=0;x<64;x++){bool tip=y>=26&&Mathf.Abs(x-31.5f)<(63-y)*.85f;bool stem=y>=4&&y<34&&Mathf.Abs(x-31.5f)<7;texture.SetPixel(x,y,(tip||stem)?Color.white:Color.clear);}texture.Apply();AssetDatabase.CreateAsset(texture,path);sprite=Sprite.Create(texture,new Rect(0,0,64,64),new Vector2(.5f,.5f));sprite.name="QuestDirection";AssetDatabase.AddObjectToAsset(sprite,texture);return sprite;}
 static void UI()
 {
 var hud=UnityEngine.Object.FindAnyObjectByType<QuestHUDUI>();var panel=Field<GameObject>(hud,"hudContainer");panel.transform.SetParent(hud.GetComponentInParent<Canvas>().transform.Find("SafeArea"),false);Rect(panel,new Vector2(1,1),new Vector2(1,1),new Vector2(-40,-40),new Vector2(440,235));panel.GetComponent<Image>().color=new Color(.035f,.07f,.09f,.92f);
 Label(panel.transform,"QuestHeading","QUEST",new Vector2(0,1),new Vector2(0,1),new Vector2(24,-18),new Vector2(330,25),18).color=new Color(.46f,.85f,.77f);
 var title=Field<TextMeshProUGUI>(hud,"questTitleText");Rect(title.gameObject,new Vector2(0,1),new Vector2(0,1),new Vector2(24,-50),new Vector2(392,60));title.fontSize=25;title.enableAutoSizing=false;
 var objective=Field<TextMeshProUGUI>(hud,"questObjectiveText");Rect(objective.gameObject,new Vector2(0,1),new Vector2(0,1),new Vector2(24,-119),new Vector2(392,75));objective.fontSize=21;objective.enableAutoSizing=false;
 var story=UnityEngine.Object.FindAnyObjectByType<ChapterPresentationUI>();var nav=story.GetComponent<MissionNavigationHint>();var distance=Field<TMP_Text>(nav,"hintText");distance.transform.SetParent(panel.transform,false);Rect(distance.gameObject,new Vector2(1,0),new Vector2(1,0),new Vector2(-24,18),new Vector2(250,28));distance.fontSize=18;distance.alignment=TextAlignmentOptions.Right;distance.color=new Color(.56f,.75f,.76f);
 var arrow=Child(panel.transform,"DirectionArrow",true);Rect(arrow,new Vector2(0,0),new Vector2(.5f,.5f),new Vector2(38,30),new Vector2(25,25));var arrowImage=C<Image>(arrow);arrowImage.sprite=Arrow();arrowImage.color=new Color(.46f,.85f,.77f);arrowImage.raycastTarget=false;Ref(nav,"directionArrow",arrow.GetComponent<RectTransform>());
 var header=Field<TextMeshProUGUI>(story,"chapterText");header.transform.parent.gameObject.SetActive(false);var learning=story.GetComponent<StoryLearningHint>();learning.enabled=false;Field<TMP_Text>(learning,"text").gameObject.SetActive(false);
 var dialogue=UnityEngine.Object.FindAnyObjectByType<DialogueUI>();var dp=Field<GameObject>(dialogue,"dialoguePanel");Rect(dp,new Vector2(.5f,0),new Vector2(.5f,0),new Vector2(0,40),new Vector2(1380,225));dp.GetComponent<Image>().color=new Color(.035f,.07f,.09f,.95f);
 var name=Field<TextMeshProUGUI>(dialogue,"speakerNameText");Rect(name.gameObject,new Vector2(0,1),new Vector2(0,1),new Vector2(28,-22),new Vector2(1040,34));name.fontSize=25;name.color=new Color(.58f,.89f,.82f);
 var body=Field<TextMeshProUGUI>(dialogue,"dialogueText");Rect(body.gameObject,new Vector2(0,1),new Vector2(0,1),new Vector2(28,-74),new Vector2(1324,98));body.fontSize=26;body.enableAutoSizing=false;
 var next=Field<Button>(dialogue,"continueButton");Rect(next.gameObject,new Vector2(1,0),new Vector2(1,0),new Vector2(-24,16),new Vector2(185,35));foreach(var label in next.GetComponentsInChildren<TMP_Text>()){label.fontSize=20;label.text="Lanjut";}
 var skip=Field<Button>(story,"skipButton");skip.transform.SetParent(dp.transform,false);Rect(skip.gameObject,new Vector2(1,1),new Vector2(1,1),new Vector2(-24,-17),new Vector2(245,42));foreach(var text in skip.GetComponentsInChildren<TMP_Text>()){text.fontSize=19;text.text="Lewati pembukaan";}
 var quiz=UnityEngine.Object.FindAnyObjectByType<QuizUI>();var card=Field<GameObject>(quiz,"panelRoot");Rect(card,new Vector2(.5f,.5f),new Vector2(.5f,.5f),Vector2.zero,new Vector2(880,500));card.GetComponent<Image>().color=new Color(.035f,.07f,.09f,.98f);
 card.GetComponent<Image>().sprite=null;dp.GetComponent<Image>().sprite=null;panel.GetComponent<Image>().sprite=null;
 Label(card.transform,"Heading","QUEST • PILIH TANGGAPAN",new Vector2(0,1),new Vector2(0,1),new Vector2(30,-25),new Vector2(810,30),19).color=new Color(.46f,.85f,.77f);
 var content=Child(card.transform,"QuestionContent",true);Rect(content,new Vector2(0,1),new Vector2(0,1),new Vector2(30,-76),new Vector2(820,390));Ref(quiz,"questionContent",content);
 var question=Field<TextMeshProUGUI>(quiz,"questionText");question.transform.SetParent(content.transform,false);Rect(question.gameObject,new Vector2(0,1),new Vector2(0,1),Vector2.zero,new Vector2(820,120));question.fontSize=27;question.enableAutoSizing=false;
 var so=new SerializedObject(quiz);var buttons=so.FindProperty("optionButtons");for(int i=0;i<buttons.arraySize;i++){var btn=(Button)buttons.GetArrayElementAtIndex(i).objectReferenceValue;btn.transform.SetParent(content.transform,false);Rect(btn.gameObject,new Vector2(0,1),new Vector2(0,1),new Vector2(0,-142-i*78),new Vector2(820,66));btn.GetComponent<Image>().color=new Color(.10f,.22f,.25f);foreach(var text in btn.GetComponentsInChildren<TMP_Text>()){Rect(text.gameObject,new Vector2(.5f,.5f),new Vector2(.5f,.5f),Vector2.zero,new Vector2(780,58));text.fontSize=23;text.enableAutoSizing=false;text.alignment=TextAlignmentOptions.MidlineLeft;}}
 var feedback=Field<GameObject>(quiz,"feedbackPanel");Rect(feedback,new Vector2(0,1),new Vector2(0,1),new Vector2(30,-78),new Vector2(820,318));var feedbackImage=feedback.GetComponent<Image>();if(feedbackImage!=null)feedbackImage.color=Color.clear;
 var result=Field<TextMeshProUGUI>(quiz,"feedbackResultText");Rect(result.gameObject,new Vector2(0,1),new Vector2(0,1),Vector2.zero,new Vector2(820,55));result.fontSize=29;result.color=new Color(.58f,.89f,.82f);
 var explanation=Field<TextMeshProUGUI>(quiz,"feedbackExplanationText");Rect(explanation.gameObject,new Vector2(0,1),new Vector2(0,1),new Vector2(0,-78),new Vector2(820,225));explanation.fontSize=26;explanation.enableAutoSizing=false;
 var proceed=Field<Button>(quiz,"continueButton");Rect(proceed.gameObject,new Vector2(1,0),new Vector2(1,0),new Vector2(-30,25),new Vector2(210,48));foreach(var t in proceed.GetComponentsInChildren<TMP_Text>())t.fontSize=22;
 // Actor names belong in dialogue. Remove labels that duplicate the visible character/quest.
 foreach(var label in UnityEngine.Object.FindObjectsByType<WorldCharacterLabel>(FindObjectsInactive.Include))label.gameObject.SetActive(false);
 var choices=story.transform.Find("SafeArea/AjiChoices");if(choices!=null){Rect(choices.gameObject,new Vector2(.5f,0),new Vector2(.5f,0),new Vector2(0,282),new Vector2(1380,300));choices.GetComponent<Image>().sprite=null;choices.GetComponent<Image>().color=new Color(.035f,.07f,.09f,.98f);var heading=choices.Find("Heading").GetComponent<TMP_Text>();heading.text="Pilih respons Aji";heading.fontSize=21;Rect(heading.gameObject,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-15),new Vector2(1320,34));for(int i=0;i<3;i++){var choice=choices.Find("Choice"+i);Rect(choice.gameObject,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-60-i*77),new Vector2(1320,62));choice.GetComponent<Image>().sprite=null;}}
 var activity=UnityEngine.Object.FindAnyObjectByType<NarrativeActivityDirector>();var math=Field<GameObject>(activity,"mathPanel");Rect(math,new Vector2(.5f,0),new Vector2(.5f,0),new Vector2(0,35),new Vector2(880,360));math.GetComponent<Image>().sprite=null;var instruction=Field<TMP_Text>(activity,"instruction");Rect(instruction.gameObject,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-20),new Vector2(820,90));var mathButtons=new SerializedObject(activity).FindProperty("answerButtons");for(int i=0;i<mathButtons.arraySize;i++){var btn=(Button)mathButtons.GetArrayElementAtIndex(i).objectReferenceValue;Rect(btn.gameObject,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-122-i*74),new Vector2(820,60));}
 }
 public static string ScenePass()
 {
 if(Application.isPlaying)throw new Exception("Edit Mode required");EditorSceneManager.OpenScene(BaseScene);UI();
 var classroom=GameObject.Find("_Level/Environtment/ExpandedCampus/Classroom");if(classroom!=null){var boardTransform=classroom.transform.Find("Board");if(boardTransform!=null)boardTransform.localPosition=new Vector3(0,2.6f,4.84f);var boardText=classroom.transform.Find("BoardText");if(boardText!=null)boardText.localPosition=new Vector3(0,2.7f,4.75f);}
 if(classroom!=null)for(int i=0;i<6;i++){float x=i%2==0?-3.5f:3.5f;float z=-3.2f+(i/2)*1.5f;var desk=classroom.transform.Find("Desk_"+i);if(desk!=null)desk.localPosition=new Vector3(x,.7f,z);var chair=classroom.transform.Find("Chair_"+i);if(chair!=null)chair.localPosition=new Vector3(x,.45f,z-.9f);}
 var activity=UnityEngine.Object.FindAnyObjectByType<NarrativeActivityDirector>();var points=Child(GameObject.Find("_Level").transform,"ClassroomBlocking");var board=Child(points.transform,"DenisAtBoard");Place(board.transform,new Vector3(-20,.05f,17),0);Ref(activity,"arithmeticStage",board.transform);
 var dialogueRig=GameObject.Find("Cameras/DialogueCamera").GetComponent<BullyingGame.Camera.DialogueCameraFraming>();var dialogueFocus=Child(GameObject.Find("Cameras").transform,"DialogueFocus");Ref(dialogueRig,"compositionTarget",dialogueFocus.transform);dialogueRig.GetComponent<CinemachineCamera>().LookAt=dialogueFocus.transform;
 var camera=Child(points.transform,"GroupShot");camera.transform.position=new Vector3(-20,2.65f,10.65f);camera.transform.rotation=Quaternion.LookRotation(new Vector3(-20,.75f,16.2f)-camera.transform.position);Ref(activity,"arithmeticCameraAnchor",camera.transform);
 var positions=new[]{new Vector3(-18.5f,.05f,16.2f),new Vector3(-17,.05f,16.2f),new Vector3(-15.5f,.05f,16.2f)};var stages=positions.Select((p,i)=>{var g=Child(points.transform,"Bully"+i);Place(g.transform,p,0);return (UnityEngine.Object)g.transform;}).ToArray();Refs(activity,"arithmeticGangPoints",stages);
 camera.transform.rotation=Quaternion.LookRotation(new Vector3(-19.4f,.75f,16.2f)-camera.transform.position);
 var teacher=GameObject.Find("_Level/PakBambang").transform;var stand=teacher.Find("PlayerDialogueSpawnPoint")??teacher.Find("DialogueSpawnPoint");if(stand!=null)stand.localPosition=new Vector3(-1.7f,0,1.6f);var anchor=Child(teacher,"DialogueCameraAnchor");anchor.transform.localPosition=new Vector3(-1.6f,1.9f,4.8f);
 var poses=UnityEngine.Object.FindAnyObjectByType<StoryChapterSequence>().GetComponent<ChapterActorLayout>();Edit(poses,s=>{var list=s.FindProperty("poses");for(int i=0;i<list.arraySize;i++){var pose=list.GetArrayElementAtIndex(i);if(pose.FindPropertyRelative("chapter").intValue==2 && pose.FindPropertyRelative("actor").objectReferenceValue==teacher)pose.FindPropertyRelative("position").vector3Value=new Vector3(-22.5f,.05f,17);}});
 var sequence=UnityEngine.Object.FindAnyObjectByType<StoryChapterSequence>();Edit(sequence,s=>s.FindProperty("sceneChapterNumber").intValue=1);Opening(1);EditorSceneManager.MarkSceneDirty(sequence.gameObject.scene);EditorSceneManager.SaveScene(sequence.gameObject.scene);
 for(int number=2;number<=5;number++)
 {
 string folder="Assets/_Game/Scenes/Levels/Level_0"+number;if(!AssetDatabase.IsValidFolder(folder))AssetDatabase.CreateFolder("Assets/_Game/Scenes/Levels","Level_0"+number);string path=folder+"/Level0"+number+".unity";EditorSceneManager.SaveScene(sequence.gameObject.scene,path,true);EditorSceneManager.OpenScene(path);sequence=UnityEngine.Object.FindAnyObjectByType<StoryChapterSequence>();Edit(sequence,s=>s.FindProperty("sceneChapterNumber").intValue=number);sequence.GetComponent<OutdoorChapterPresentation>().Apply(number-1);sequence.GetComponent<ChapterActorLayout>().Apply(number);var pov=UnityEngine.Object.FindAnyObjectByType<PlayablePOVController>();pov.Apply(Load<NarrativeChapterData>("Chapter0"+number).Perspective);var book=UnityEngine.Object.FindAnyObjectByType<QuestItem>();if(book!=null)book.gameObject.SetActive(false);Opening(number);EditorSceneManager.MarkSceneDirty(sequence.gameObject.scene);EditorSceneManager.SaveScene(sequence.gameObject.scene);EditorSceneManager.OpenScene(BaseScene);sequence=UnityEngine.Object.FindAnyObjectByType<StoryChapterSequence>();
 }
 EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene("Assets/_Game/Scenes/00_Bootstrap/00_Bootstrap.unity",true),new EditorBuildSettingsScene("Assets/_Game/Scenes/01_MainMenu/01_MainMenu.unity",true)}.Concat(Enumerable.Range(1,5).Select(i=>new EditorBuildSettingsScene("Assets/_Game/Scenes/Levels/Level_0"+i+"/Level0"+i+".unity",true))).ToArray();
 EditorSceneManager.OpenScene("Assets/_Game/Scenes/01_MainMenu/01_MainMenu.unity");Refs(UnityEngine.Object.FindAnyObjectByType<MainMenuFlow>(),"chapters",Enumerable.Range(1,5).Select(i=>(UnityEngine.Object)Load<NarrativeChapterData>("Chapter0"+i)).ToArray());EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene());AssetDatabase.SaveAssets();EditorSceneManager.OpenScene(BaseScene);return "Saved clean HUD/question UI, classroom blocking, five separate scene hosts, per-character Timeline shots and menu chapter routing.";
 }
 public static string QuestionTidy()
 {
 Edit(Load<NarrativeChapterData>("Chapter01"),s=>s.FindProperty("reflections").GetArrayElementAtIndex(1).FindPropertyRelative("questionText").stringValue="Kelompok Billy mengancam dan mencoba merebut buku Denis. Siapa yang bertanggung jawab atas tindakan itu?");AssetDatabase.SaveAssets();return "Question applies to either notebook outcome.";
 }
 static void Opening(int number)
 {
 var opening=UnityEngine.Object.FindAnyObjectByType<StoryOpeningDirector>();var director=Field<PlayableDirector>(opening,"timeline");var previous=(TimelineAsset)director.playableAsset;var receiver=C<SignalReceiver>(director.gameObject);SignalAsset signal=null;UnityEngine.Events.UnityEvent reaction=null;
 for(int i=0;i<receiver.Count();i++){var e=receiver.GetReactionAtIndex(i);if(e!=null&&e.GetPersistentEventCount()>0&&e.GetPersistentMethodName(0)=="StartOpeningDialogue"){signal=receiver.GetSignalAssetAtIndex(i);reaction=e;break;}}
 if(signal==null)throw new Exception("Opening signal/reaction missing");
 string assetPath=Art+"TL_Level0"+number+"_Opening.playable";var timeline=AssetDatabase.LoadAssetAtPath<TimelineAsset>(assetPath);if(timeline==null){timeline=ScriptableObject.CreateInstance<TimelineAsset>();AssetDatabase.CreateAsset(timeline,assetPath);}foreach(var t in timeline.GetOutputTracks().ToArray())timeline.DeleteTrack(t);
 var track=timeline.CreateTrack<CinemachineTrack>(null,"Character introductions");director.playableAsset=timeline;director.SetGenericBinding(track,UnityEngine.Object.FindAnyObjectByType<CinemachineBrain>());
 var names=new[]{"Aji","Denis","Billy","Bima","Fajar","Ari","Pak Bambang","Bu Sari"};var actorPaths=new[]{"_Level/StoryCharacters/Aji","_Level/StoryCharacters/Denis","_Level/BullyGroup/Bully_Leader","_Level/BullyGroup/Bully_Friends","_Level/BullyGroup/Bully_Friends 2","_Level/StoryCharacters/Ari","_Level/PakBambang","_Level/StoryCharacters/KantinVendor"};var actors=actorPaths.Select(p=>GameObject.Find(p)??UnityEngine.Object.FindObjectsByType<Transform>(FindObjectsInactive.Include).First(t=>t.name==p.Split('/').Last()).gameObject).Select(g=>g.transform).ToArray();
 var stage=GameObject.Find("_Level/OpeningStage").transform;var locations=number==2?new[]{new Vector3(-22,0,14),new Vector3(-20,0,17),new Vector3(-18.2f,0,16.2f),new Vector3(-17,0,15.7f),new Vector3(-19,0,15.3f),new Vector3(-23,0,15.4f),new Vector3(-22,0,17.5f),new Vector3(-24,0,13)}:new[]{new Vector3(-2,0,-.5f),new Vector3(0,0,1.1f),new Vector3(1.5f,0,2.3f),new Vector3(2.7f,0,3),new Vector3(3.3f,0,1.4f),new Vector3(-3.8f,0,2.7f),new Vector3(-5,0,5),new Vector3(-5,0,-1.5f)};
 var stageObjects=locations.Select((p,i)=>{var g=Child(stage,"Cast_"+names[i].Replace(" ",""));Place(g.transform,p+Vector3.up*.05f,number==2?180:160);return (UnityEngine.Object)g.transform;}).ToArray();Refs(opening,"actors",actors.Cast<UnityEngine.Object>().ToArray());Refs(opening,"stagePoints",stageObjects);
 var rig=Child(GameObject.Find("Cameras").transform,"OpeningShots").transform;
 Action<string,double,double,Vector3,Vector3,float> shot=(n,start,duration,position,focus,fov)=>{var g=Child(rig,n);g.transform.SetPositionAndRotation(position,Quaternion.LookRotation(focus-position));var cam=C<CinemachineCamera>(g);cam.Priority=0;cam.Lens.FieldOfView=fov;var clip=track.CreateClip<CinemachineShot>();clip.displayName=n;clip.start=start;clip.duration=duration;var asset=(CinemachineShot)clip.asset;asset.VirtualCamera.exposedName=new PropertyName("L"+number+"_"+n);director.SetReferenceValue(asset.VirtualCamera.exposedName,cam);};
 var widePosition=number==2?new Vector3(-20,2.7f,10.65f):new Vector3(8,3.3f,-8);var wideFocus=number==2?new Vector3(-20,.75f,16):new Vector3(-.5f,.8f,2);shot("Establishing",0,3,widePosition,wideFocus,number==2?58:49);
 Edit(opening,s=>{var speakers=s.FindProperty("speakers");speakers.arraySize=names.Length;for(int i=0;i<names.Length;i++){var focus=locations[i]+Vector3.up*1.25f;var position=number==2?new Vector3(locations[i].x,2f,Mathf.Max(11,locations[i].z-3.8f)):locations[i]+new Vector3(1.7f,1.75f,-3.6f);if(number==2&&i==2){position=widePosition;focus=wideFocus;}double start=3+i*3;shot("Introduce_"+names[i].Replace(" ",""),start,3,position,focus,number==2&&i==2?58:45);var entry=speakers.GetArrayElementAtIndex(i);entry.FindPropertyRelative("speaker").stringValue=names[i];entry.FindPropertyRelative("actor").objectReferenceValue=actors[i];entry.FindPropertyRelative("shot").objectReferenceValue=rig.Find("Introduce_"+names[i].Replace(" ","")).GetComponent<CinemachineCamera>();entry.FindPropertyRelative("timelineTime").floatValue=(float)start+.3f;}});
 shot("Closing",27,2,widePosition,wideFocus,number==2?58:49);var signals=timeline.CreateTrack<SignalTrack>(null,"Pause for opening dialogue");var marker=signals.CreateMarker<SignalEmitter>(.8);marker.asset=signal;marker.emitOnce=true;director.SetGenericBinding(signals,receiver);EditorUtility.SetDirty(timeline);EditorUtility.SetDirty(director);
 }
}
